# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('vehicle', 'Vehicle / Equipment'), ('company', 'Company (general)')], max_length=12)),
                ('direction', models.CharField(choices=[('in', 'Received (money in)'), ('out', 'Paid (money out)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('online', 'Online / Wallet'), ('credit', 'Credit (unpaid)')], default='cash', max_length=10)),
                ('payment_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('vehicle', 'Vehicle / Equipment'), ('company', 'Company (general)')], max_length=12)),
                ('account_id', models.PositiveBigIntegerField(blank=True, help_text='PK of the customer/supplier/employee/vehicle account.', null=True)),
                ('entry_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ledger entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
    ]
