# Generated by Django 6.0.6 on 2026-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='account_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='PK of the party account; empty for company-level accounts.', null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('employee', 'Employee'), ('vehicle', 'Vehicle / Equipment'), ('sales', 'Sales Account'), ('purchase', 'Purchase Account'), ('expense', 'Expense Account'), ('cash', 'Cash / Bank')], max_length=12),
        ),
    ]
