# Generated by Django 6.0.6 on 2026-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_ledgerentry_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the voucher / reference.', null=True, upload_to='references/payments/%Y/%m/'),
        ),
    ]
