# Generated by Django 6.0.6 on 2026-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_payment_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
