# Generated by Django 6.0.6 on 2026-10-08 09:52

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_payment_reference_id_payment_reference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the voucher / reference.', null=True, upload_to=core.uploads.ReferenceImagePath('payments', 'reference_no')),
        ),
    ]
