# Generated by Django 6.0.6 on 2026-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the receipt / reference.', null=True, upload_to='references/expenses/%Y/%m/'),
        ),
    ]
