# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='NPR', max_length=8)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired (read-only)'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='subscriptions.saasplan')),
            ],
            options={
                'verbose_name': 'Tenant Company',
                'verbose_name_plural': 'Tenant Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='tenants.tenantcompany')),
            ],
            options={
                'ordering': ['tenant', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_depot_name_per_tenant')],
            },
        ),
    ]
