# Generated by Django 6.0.6 on 2026-10-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('default_currency', models.CharField(default='NPR', max_length=8)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('subscription_status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('grace', 'Grace Period'), ('expired', 'Expired (read-only)'), ('suspended', 'Suspended')], default='trial', max_length=20)),
                ('subscription_start', models.DateField(blank=True, null=True)),
                ('subscription_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, help_text='Company logo shown on invoices.', null=True, upload_to='tenant_logos/')),
                ('default_calendar', models.CharField(choices=[('AD', 'English date (AD)'), ('BS', 'Nepali date (BS)')], default='AD', help_text='Default calendar shown to this company’s users.', max_length=2)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='subscriptions.saasplan')),
            ],
            options={
                'verbose_name': 'Tenant Company',
                'verbose_name_plural': 'Tenant Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=200, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('from_email', models.EmailField(max_length=254, verbose_name='From address')),
                ('from_name', models.CharField(blank=True, max_length=200, verbose_name='From name')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='tenants.tenantcompany')),
            ],
            options={
                'verbose_name': 'Email (SMTP) configuration',
                'verbose_name_plural': 'Email (SMTP) configurations',
            },
        ),
        migrations.CreateModel(
            name='TenantMessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='977', help_text='Added to local numbers for Twilio / WhatsApp, e.g. 977 for Nepal.', max_length=5, verbose_name='Default country code')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='Enable SMS')),
                ('sms_provider', models.CharField(choices=[('sparrow', 'Sparrow SMS'), ('aakash', 'Aakash SMS'), ('twilio', 'Twilio')], default='sparrow', max_length=10, verbose_name='SMS provider')),
                ('sms_token', models.CharField(blank=True, help_text='Sparrow/Aakash token, or the Twilio auth token.', max_length=255, verbose_name='SMS API token')),
                ('sms_account_sid', models.CharField(blank=True, help_text='Twilio only.', max_length=100, verbose_name='SMS account SID')),
                ('sms_sender', models.CharField(blank=True, help_text='Sparrow "identity" or Twilio "from" number. Not used by Aakash.', max_length=50, verbose_name='SMS sender')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Enable WhatsApp')),
                ('whatsapp_provider', models.CharField(choices=[('meta', 'WhatsApp Cloud API (Meta)'), ('twilio', 'Twilio')], default='meta', max_length=10, verbose_name='WhatsApp provider')),
                ('whatsapp_token', models.CharField(blank=True, help_text='Meta permanent access token, or the Twilio auth token.', max_length=500, verbose_name='WhatsApp access token')),
                ('whatsapp_account_sid', models.CharField(blank=True, help_text='Twilio only.', max_length=100, verbose_name='WhatsApp account SID')),
                ('whatsapp_sender', models.CharField(blank=True, help_text='Meta "phone number ID", or the Twilio WhatsApp number (e.g. +14155238886).', max_length=50, verbose_name='WhatsApp sender')),
                ('whatsapp_template', models.CharField(blank=True, help_text="Meta only. Approved template with 4 body variables: customer, invoice no, amount, link. Leave blank to send plain text (Meta only delivers that within 24h of the customer's last message).", max_length=100, verbose_name='WhatsApp template name')),
                ('whatsapp_template_language', models.CharField(blank=True, default='en', max_length=10, verbose_name='Template language')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='tenants.tenantcompany')),
            ],
            options={
                'verbose_name': 'SMS / WhatsApp configuration',
                'verbose_name_plural': 'SMS / WhatsApp configurations',
            },
        ),
        migrations.CreateModel(
            name='DepotLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='tenants.tenantcompany')),
            ],
            options={
                'ordering': ['tenant', 'name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='unique_depot_name_per_tenant')],
            },
        ),
    ]
