# Generated by Django 6.0.6 on 2026-06-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompany',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo shown on invoices.', null=True, upload_to='tenant_logos/'),
        ),
        migrations.CreateModel(
            name='TenantEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=200, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True, verbose_name='Use TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Use SSL')),
                ('from_email', models.EmailField(max_length=254, verbose_name='From address')),
                ('from_name', models.CharField(blank=True, max_length=200, verbose_name='From name')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='tenants.tenantcompany')),
            ],
            options={
                'verbose_name': 'Email (SMTP) configuration',
                'verbose_name_plural': 'Email (SMTP) configurations',
            },
        ),
    ]
