# Generated by Django 6.0.6 on 2026-06-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenantcompany_logo_tenantemailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantcompany',
            name='default_calendar',
            field=models.CharField(choices=[('AD', 'English date (AD)'), ('BS', 'Nepali date (BS)')], default='AD', help_text='Default calendar shown to this company’s users.', max_length=2),
        ),
    ]
