# Generated by Django 6.0.6 on 2026-10-08 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantcompany_default_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(default='977', help_text='Added to local numbers for Twilio / WhatsApp, e.g. 977 for Nepal.', max_length=5, verbose_name='Default country code')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='Enable SMS')),
                ('sms_provider', models.CharField(choices=[('sparrow', 'Sparrow SMS'), ('aakash', 'Aakash SMS'), ('twilio', 'Twilio')], default='sparrow', max_length=10, verbose_name='SMS provider')),
                ('sms_token', models.CharField(blank=True, help_text='Sparrow/Aakash token, or the Twilio auth token.', max_length=255, verbose_name='SMS API token')),
                ('sms_account_sid', models.CharField(blank=True, help_text='Twilio only.', max_length=100, verbose_name='SMS account SID')),
                ('sms_sender', models.CharField(blank=True, help_text='Sparrow "identity" or Twilio "from" number. Not used by Aakash.', max_length=50, verbose_name='SMS sender')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='Enable WhatsApp')),
                ('whatsapp_provider', models.CharField(choices=[('meta', 'WhatsApp Cloud API (Meta)'), ('twilio', 'Twilio')], default='meta', max_length=10, verbose_name='WhatsApp provider')),
                ('whatsapp_token', models.CharField(blank=True, help_text='Meta permanent access token, or the Twilio auth token.', max_length=500, verbose_name='WhatsApp access token')),
                ('whatsapp_account_sid', models.CharField(blank=True, help_text='Twilio only.', max_length=100, verbose_name='WhatsApp account SID')),
                ('whatsapp_sender', models.CharField(blank=True, help_text='Meta "phone number ID", or the Twilio WhatsApp number (e.g. +14155238886).', max_length=50, verbose_name='WhatsApp sender')),
                ('whatsapp_template', models.CharField(blank=True, help_text="Meta only. Approved template with 4 body variables: customer, invoice no, amount, link. Leave blank to send plain text (Meta only delivers that within 24h of the customer's last message).", max_length=100, verbose_name='WhatsApp template name')),
                ('whatsapp_template_language', models.CharField(blank=True, default='en', max_length=10, verbose_name='Template language')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messaging_config', to='tenants.tenantcompany')),
            ],
            options={
                'verbose_name': 'SMS / WhatsApp configuration',
                'verbose_name_plural': 'SMS / WhatsApp configurations',
            },
        ),
    ]
