# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('total_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('sold_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('excess_qty', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('trip_status', models.CharField(choices=[('open', 'Open'), ('split', 'Split Allocated'), ('closed', 'Closed')], default='open', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('purchase_date', models.DateField()),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unloading_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
