# Generated by Django 6.0.6 on 2026-06-05 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
        ('purchases', '0003_purchase_vehicle_trip_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_expense_lines', to='expenses.expensecategory')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='purchases.purchase')),
            ],
        ),
    ]
