# Generated by Django 6.0.6 on 2026-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the bill / reference.', null=True, upload_to='references/purchases/%Y/%m/'),
        ),
    ]
