# Generated by Django 6.0.6 on 2026-06-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('saas_super_admin', 'SaaS Super Admin'), ('saas_staff', 'SaaS Staff'), ('client_owner', 'Client Owner'), ('client_admin', 'Client Admin / Accountant'), ('depot_admin', 'Depot Admin / Location Manager'), ('billing_user', 'Sales / Billing User'), ('stock_user', 'Purchase / Stock User'), ('viewer', 'Read-Only Viewer'), ('staff', 'Staff')], default='viewer', max_length=32),
        ),
    ]
