# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('unit_type', models.CharField(choices=[('hour', 'Hour'), ('day', 'Day'), ('trip', 'Trip')], default='hour', max_length=10)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase In'), ('purchase_excess', 'Split/Excess In'), ('transfer_in', 'Transfer In'), ('adjust_in', 'Adjustment In'), ('sale', 'Sale Out'), ('transfer_out', 'Transfer Out'), ('damage', 'Damage / Loss Out'), ('adjust_out', 'Adjustment Out')], max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('qty_in', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_out', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Plate number or nickname.', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleCapacityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_factor', models.DecimalField(decimal_places=4, help_text='1 from-vehicle = factor × to-vehicle/base-unit.', max_digits=10)),
            ],
            options={
                'ordering': ['from_vehicle_type'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('default_capacity', models.DecimalField(decimal_places=3, default=1, help_text='Standard capacity expressed in the capacity unit.', max_digits=12)),
                ('capacity_unit', models.CharField(default='cubic_feet', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('base_unit', models.CharField(default='cubic_feet', help_text='Base unit for internal stock, e.g. cubic feet, brass, ton, Nissan-load.', max_length=40)),
                ('default_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('default_sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
