# Generated by Django 6.0.6 on 2026-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Warn when stock in a depot falls to or below this (base unit). 0 = no warning.', max_digits=14),
        ),
    ]
