"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j!_n#-c4#my0i9^n^%6xqo-9*nh-8%b_u)2o^_=e(=buq7bwxm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

# DepotLedger SaaS apps (see SRS section 12.1).
LOCAL_APPS = [
    'core',           # Shared abstract base models, mixins and helpers.
    'accounts',       # Custom user, profiles, roles and authentication.
    'tenants',        # Client companies (tenants) and depot/warehouse locations.
    'subscriptions',  # SaaS plans, subscriptions and usage/entry billing.
    'inventory',      # Materials, services, vehicles, capacity rules, stock ledger.
    'parties',        # Customers and suppliers.
    'purchases',      # Purchases and incoming trips / load splits.
    'sales',          # Sale invoices, invoice lines and delivery logs.
    'ledger',         # Ledger entries, payments and accounting services.
    'expenses',       # Expense categories and expense entries.
    'employees',      # Employees, work logs and payroll.
    'reports',        # Dashboard and financial/stock reports.
    'audit',          # Audit logs and activity tracking.
]

INSTALLED_APPS = DJANGO_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CurrentTenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# SQLite is used for local development so the scaffold runs out of the box.
# For production the SRS (section 1.4) requires PostgreSQL for strong tenant
# isolation — swap to django.db.backends.postgresql once psycopg is installed.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Languages offered in the UI switcher (SRS NFR: Localization — English/Nepali).
LANGUAGES = [
    ('en', 'English'),
    ('ne', 'नेपाली'),
]
LOCALE_PATHS = [BASE_DIR / 'locale']

# Nepal Time — the target market is Nepali construction suppliers (SRS NFR: Localization).
TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True

# Default currency for invoices/ledgers (SRS NFR: NPR currency support).
DEFAULT_CURRENCY = 'NPR'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files (invoice PDFs, attachments). SRS recommends S3 in production.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Map Django message levels to Bootstrap alert classes.
from django.contrib.messages import constants as message_constants  # noqa: E402

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

# Custom user model (SRS section 12.1: accounts app owns authentication).
AUTH_USER_MODEL = 'accounts.User'

# Authentication redirects.
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'reports:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'
