# Generated by Django 6.0.6 on 2026-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('cancel', 'Cancel / Void'), ('payment', 'Payment'), ('email', 'Email / Share'), ('subscription', 'Subscription Change'), ('login', 'Login'), ('logout', 'Logout'), ('impersonate', 'Support Impersonation')], max_length=20),
        ),
    ]
