# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('billing_cycle', models.CharField(choices=[('trial', 'Trial'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom'), ('pay_per_entry', 'Pay Per Entry'), ('hybrid', 'Hybrid')], default='monthly', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('per_entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('depot_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('entry_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_limit_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('features_json', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('invoice_count', models.PositiveIntegerField(default=0)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('sms_count', models.PositiveIntegerField(default=0)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('grace_days', models.PositiveIntegerField(default=0)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('custom_per_entry_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.saasplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
