# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenantcompany'),
        ),
        migrations.AddField(
            model_name='subscriptionusage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenants.tenantcompany'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionusage',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_start', 'period_end'), name='unique_usage_period_per_tenant'),
        ),
    ]
