# Generated by Django 6.0.6 on 2026-06-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        ('parties', '0002_initial'),
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenantcompany'),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='parties.customer'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='tenants.depotlocation'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.tenantcompany'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverylog',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='sales.saleinvoice'),
        ),
        migrations.AddField(
            model_name='saleinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.saleinvoice'),
        ),
        migrations.AddField(
            model_name='saleinvoiceline',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.materialitem'),
        ),
        migrations.AddField(
            model_name='saleinvoiceline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.serviceitem'),
        ),
        migrations.AddField(
            model_name='saleinvoiceline',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='inventory.vehicletype'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['tenant', 'depot', 'invoice_date'], name='sales_salei_tenant__90b33f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['tenant', 'customer'], name='sales_salei_tenant__70ef58_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_no'), name='unique_invoice_no_per_tenant'),
        ),
    ]
