# Generated by Django 6.0.6 on 2026-10-08 09:52

import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleinvoice_reference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoice',
            name='reference_image',
            field=models.ImageField(blank=True, help_text='Optional photo of the bill / reference.', null=True, upload_to=core.uploads.ReferenceImagePath('invoices', 'invoice_no')),
        ),
    ]
